// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwA_OE7OYQSc06XQxvSvi-pe5qfltbUtA',
    appId: '1:1047527445608:android:a738422f5a5e90e91c17dd',
    messagingSenderId: '1047527445608',
    projectId: 'dhanmanthan-d5cec',
    storageBucket: 'dhanmanthan-d5cec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYdjzKJYOOVL7vPk6EoVAmcIIS0bNbB88',
    appId: '1:1047527445608:ios:d35f09c5b4bd15961c17dd',
    messagingSenderId: '1047527445608',
    projectId: 'dhanmanthan-d5cec',
    storageBucket: 'dhanmanthan-d5cec.firebasestorage.app',
    iosClientId: '1047527445608-6ajf6s8rqp33pi1suvj8r21b9r03quo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhanManthan',
  );
}
